### ISSUE TITLE
Traveler Diary or Traveller Diary?

### ISSUE THREAD

**Issue by bluet** [Traveler-Diary/LandingPage#1]
一個 l 或兩個 l 都是正確的拼法，
不過 Repo name 是一個 l，landingg page 只有 https://github.com/Traveler-Diary/LandingPage/blob/master/index.html#L40 是一個 l 其他都是兩個 l，
似乎要統一一下 XD

**Comment by a10000005588** [comment]
好的，目前正常英文用法多數為 一個 l 我們小組在商卻看看要不要用兩個 ll 來讓我們的名稱更有特色之類的，討論好會馬上作更正

**Comment by bluet** [comment]
@a10000005588 用兩個 l 怕反而會讓使用者搜尋不到 XD
修正的話，還麻煩關閉這個 issue 喔

**Comment by a10000005588** [comment]
糟糕 我們目前已經統一要用 兩個ll了 不過長遠來看忘了考量到SEO最佳化的問題 我們小組會再好好討論的 謝謝BT老師
